language: php

php:
- 5.5
- 5.6
- 7
- 7.1

env:
- WP_VERSION=latest

install:
- composer self-update
- composer install

before_script:
- ./ci/ci.sh wordpress_test root ''

script: 
- vendor/bin/behat
